-- MySQL Script generated by MySQL Workbench
-- Fri Dec 11 21:27:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema exer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exer` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `exer` ;

-- -----------------------------------------------------
-- Table `exer`.`numbers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exer`.`numbers` ;

CREATE TABLE IF NOT EXISTS `exer`.`numbers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `even_number` VARCHAR(255) NULL DEFAULT NULL,
  `factorial` INT NULL DEFAULT NULL,
  `prime_number` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
